# Generated by Django 4.2.16 on 2025-05-10 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('icone', models.CharField(max_length=100)),
                ('nombre_livres', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=100)),
                ('annee_publication', models.IntegerField()),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('emprunté', 'Emprunté')], max_length=50)),
                ('couverture', models.ImageField(upload_to='couvertures/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbiblio.categorie')),
            ],
        ),
    ]
