# Generated by Django 4.2.16 on 2025-06-16 18:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('icone', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LignePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=200)),
                ('isbn', models.CharField(default='0000000000000', max_length=13)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_litteraire', models.CharField(blank=True, max_length=255, null=True)),
                ('date_publication', models.DateField()),
                ('description', models.TextField()),
                ('couverture', models.ImageField(default='appbiblio/defaut.jpg', upload_to='couvertures/')),
                ('couverture_url', models.URLField(blank=True, max_length=500, null=True)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('emprunte', 'Emprunté'), ('réservé', 'Réservé')], default='disponible', max_length=20)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livres', to='appbiblio.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('livres', models.ManyToManyField(related_name='paniers', through='appbiblio.LignePanier', to='appbiblio.livre')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lignepanier',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbiblio.livre'),
        ),
        migrations.AddField(
            model_name='lignepanier',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_panier', to='appbiblio.panier'),
        ),
        migrations.CreateModel(
            name='HistoriqueLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('réservé', 'Réservé'), ('emprunté', 'Emprunté'), ('retourné', 'Retourné'), ('annulé', 'Annulé')], max_length=10)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbiblio.livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='EmpruntPrevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prevue_retrait', models.DateField(default=datetime.date.today)),
                ('date_prevue_retour', models.DateField()),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbiblio.livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_retrait', models.DateTimeField()),
                ('date_retour', models.DateTimeField(blank=True, null=True)),
                ('date_limite_retrait', models.DateTimeField()),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbiblio.livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lignepanier',
            unique_together={('panier', 'livre')},
        ),
    ]
