# Generated by Django 4.2.16 on 2025-05-10 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbiblio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='annee_publication',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='statut',
        ),
        migrations.AddField(
            model_name='livre',
            name='date_publication',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='livre',
            name='description',
            field=models.TextField(default='Description par défaut'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livre',
            name='editeur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='icone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nombre_livres',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='livre',
            name='couverture',
            field=models.ImageField(blank=True, null=True, upload_to='couvertures/'),
        ),
    ]
