# Generated by Django 4.2.16 on 2025-06-14 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appbiblio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignepanier',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_panier_livre', to='appbiblio.livre'),
        ),
        migrations.AlterField(
            model_name='lignepanier',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_panier', to='appbiblio.panier'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='livres',
            field=models.ManyToManyField(through='appbiblio.LignePanier', to='appbiblio.livre'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to=settings.AUTH_USER_MODEL),
        ),
    ]
