# Generated by Django 4.2.16 on 2025-05-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbiblio', '0002_remove_livre_annee_publication_remove_livre_statut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='editeur',
        ),
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='livre',
            name='couverture',
            field=models.ImageField(default='appbiblio/defaut.jpg', upload_to='couvertures/'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='date_publication',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='livre',
            name='isbn',
            field=models.CharField(default='0000000000000', max_length=13),
        ),
        migrations.AlterField(
            model_name='livre',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
