# Generated by Django 4.2.16 on 2025-06-14 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appbiblio', '0002_alter_lignepanier_livre_alter_lignepanier_panier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
