# Generated by Django 4.2.16 on 2025-06-15 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appbiblio', '0003_panier_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignepanier',
            name='quantite',
        ),
        migrations.AddField(
            model_name='lignepanier',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lignepanier',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lignepanier',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbiblio.livre'),
        ),
        migrations.AlterField(
            model_name='lignepanier',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbiblio.panier'),
        ),
        migrations.CreateModel(
            name='HistoriqueLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('réservé', 'Réservé'), ('emprunté', 'Emprunté'), ('retourné', 'Retourné'), ('annulé', 'Annulé')], max_length=10)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbiblio.livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
    ]
