# Generated by Django 4.2.16 on 2025-05-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbiblio', '0003_remove_livre_editeur_alter_livre_auteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('emprunte', 'Emprunté')], default='disponible', max_length=20),
        ),
    ]
