# Generated by Django 4.2.16 on 2025-06-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbiblio', '0004_remove_lignepanier_quantite_lignepanier_actif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignepanier',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
