# Generated by Django 4.2.16 on 2025-05-11 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appbiblio', '0004_livre_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livres', to='appbiblio.categorie'),
        ),
    ]
