# Generated by Django 4.2.16 on 2025-05-11 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appbiblio', '0005_alter_livre_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(auto_now_add=True)),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('emprunté', 'Emprunté'), ('retourné', 'Retourné')], max_length=10)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbiblio.livre')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbiblio.membre')),
            ],
        ),
    ]
