# Generated by Django 4.2.16 on 2025-06-15 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appbiblio', '0005_lignepanier_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignepanier',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_panier', to='appbiblio.panier'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='livres',
            field=models.ManyToManyField(related_name='paniers', through='appbiblio.LignePanier', to='appbiblio.livre'),
        ),
    ]
