# Generated by Django 4.2.16 on 2025-05-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbiblio', '0007_alter_emprunt_membre_delete_membre'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='prix_litteraire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
