# Generated by Django 4.2.16 on 2025-05-11 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appbiblio', '0010_remove_emprunt_statut_emprunt_utilisateur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='livres',
        ),
        migrations.AddField(
            model_name='panier',
            name='livre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appbiblio.livre'),
        ),
        migrations.AddField(
            model_name='panier',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='panier',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
