# Generated by Django 4.2.16 on 2025-05-11 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appbiblio', '0011_remove_panier_livres_panier_livre_panier_quantite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='livre',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='quantite',
        ),
        migrations.AddField(
            model_name='panier',
            name='livres',
            field=models.ManyToManyField(blank=True, to='appbiblio.livre'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
