# Generated by Django 4.2.16 on 2025-05-14 16:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appbiblio', '0012_remove_panier_livre_remove_panier_quantite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='date_emprunt',
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='membre',
        ),
        migrations.AddField(
            model_name='emprunt',
            name='date_limite_retrait',
            field=models.DateField(default='2025-05-16'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprunt',
            name='date_retrait',
            field=models.DateField(default='2025-05-14'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour',
            field=models.DateField(default='2025-05-14'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmpruntPrevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prevue_retrait', models.DateField(default=datetime.date.today)),
                ('date_prevue_retour', models.DateField()),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbiblio.livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
