# Generated by Django 4.2.16 on 2025-05-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbiblio', '0013_remove_emprunt_date_emprunt_remove_emprunt_membre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='couverture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='couverture',
            field=models.ImageField(blank=True, null=True, upload_to='couvertures/'),
        ),
    ]
