# Generated by Django 4.2.16 on 2025-05-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbiblio', '0014_livre_couverture_url_alter_livre_couverture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='couverture',
            field=models.ImageField(default='appbiblio/defaut.jpg', upload_to='couvertures/'),
        ),
    ]
