# Generated by Django 4.2.16 on 2025-05-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbiblio', '0015_alter_livre_couverture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_limite_retrait',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_retrait',
            field=models.DateTimeField(),
        ),
    ]
