# Generated by Django 4.2.16 on 2025-06-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbiblio', '0016_alter_emprunt_date_limite_retrait_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='nombre_livres',
        ),
    ]
